name: Add audio and create PR

on:
  repository_dispatch:
    types: [add_audio]

permissions:
  contents: write
  pull-requests: write

jobs:
  add_audio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare file
        run: |
          mkdir -p public/audio
          FILE_NAME="${{ github.event.client_payload.fileName }}"
          echo "${{ github.event.client_payload.content }}" | base64 --decode > "public/audio/$FILE_NAME"

      - name: Commit changes
        run: |
          BRANCH_NAME="audio/${{ github.event.client_payload.fileName }}"
          git checkout -b "$BRANCH_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/audio/${{ github.event.client_payload.fileName }}
          git commit -m "🎤 Add new wao audio: ${{ github.event.client_payload.fileName }}"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: audio/${{ github.event.client_payload.fileName }}
          commit-message: "Add new audio file"
          title: "🎤 Add audio from ${{ github.event.client_payload.user }}"
          body: |
            Uploaded via GitHub Pages form.
            File: `public/audio/${{ github.event.client_payload.fileName }}`
          labels: |
            audio
